# PostgreSQL configuration

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 6991
  host: localhost
  pool: 5

development:
  <<: *default
  database: backend_southcoastwebmain_development

test:
  <<: *default
  database: backend_southcoastwebmain_test

production:
  <<: *default
  database: backend_southcoastwebmain_production
