# PostgreSQL configuration

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 6991
  host: localhost
  pool: 5

development:
  <<: *default
  database: southcoastwebmain_development

test:
  <<: *default
  database: southcoastwebmain_test

production:
  <<: *default
  database: southcoastwebmain_production

  # Rails 8 Solid Cache requirement
  connects_to:
    database:
      writing: production
      cache: cache

# Cache database configuration
cache:
  <<: *default
  database: southcoastwebmain_cache
